@startuml
hide empty members

class Player {
    name
    symbol

    makeMove(theBoard : Board, theMove)
}

class Board {
    getCell(position)
    setCell(position, symbol)
}

class Strategy {

}

Player --> Strategy: employs

@enduml